server:
  port: 8080

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    root: ERROR
    org.springframework: INFO
    com.peeyush: INFO
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE

spring:
  application:
    name: sample-api-db-observability
  datasource:
    url: jdbc:postgresql://localhost:5432/sample-db
    username: postgres-user
    password: postgres-password
    ## connection pool
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

management:
  endpoints:
    web:
      exposure:
          include: health, loggers
  server:
    port: 4004

