server:
  port: 8080

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    root: WARN
    org.springframework: INFO
    com.peeyush: INFO


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sample-db
    username: postgres-user
    password: postgres-password
    ## connection pool
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
