version: '3.8'

services:
  postgres:
    image: 'postgres:11.13-alpine'
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres-user
      - POSTGRES_PASSWORD=postgres-password
      - POSTGRES_DB=sample-db
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  pgadmin:
     image: dpage/pgadmin4:6.4
     container_name: pgadmin4_container
     environment:
       PGADMIN_DEFAULT_EMAIL: admin@example.com
       PGADMIN_DEFAULT_PASSWORD: admin@example.com
     ports:
       - "5050:80"
     depends_on:
       - postgres

